"""Matplotlib chapter metadata — PDS Handbook (TR)."""

MPL_CHAPTER = "04-matplotlib"

MPL_SECTIONS = [
    {
        "slug": "00-introduction",
        "notebook": "04.00-Introduction-To-Matplotlib.ipynb",
        "title": "Matplotlib ile Görselleştirme",
        "nav_title": "Matplotlib'e Giriş",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/04.00-introduction-to-matplotlib.html",
        "en_label": "04.00 Introduction to Matplotlib",
        "preload_seaborn": False,
    },
    {
        "slug": "01-simple-line-plots",
        "notebook": "04.01-Simple-Line-Plots.ipynb",
        "title": "Basit Çizgi Grafikleri",
        "nav_title": "4.1 Çizgi Grafikleri",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/04.01-simple-line-plots.html",
        "en_label": "04.01 Simple Line Plots",
        "preload_seaborn": False,
    },
    {
        "slug": "02-simple-scatter-plots",
        "notebook": "04.02-Simple-Scatter-Plots.ipynb",
        "title": "Basit Saçılım Grafikleri",
        "nav_title": "4.2 Saçılım Grafikleri",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/04.02-simple-scatter-plots.html",
        "en_label": "04.02 Simple Scatter Plots",
        "preload_seaborn": False,
    },
    {
        "slug": "03-errorbars",
        "notebook": "04.03-Errorbars.ipynb",
        "title": "Hata Çubukları",
        "nav_title": "4.3 Hata Çubukları",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/04.03-errorbars.html",
        "en_label": "04.03 Errorbars",
        "preload_seaborn": False,
    },
    {
        "slug": "04-density-and-contour-plots",
        "notebook": "04.04-Density-and-Contour-Plots.ipynb",
        "title": "Yoğunluk ve Kontur Grafikleri",
        "nav_title": "4.4 Yoğunluk ve Kontur",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/04.04-density-and-contour-plots.html",
        "en_label": "04.04 Density and Contour Plots",
        "preload_seaborn": False,
    },
    {
        "slug": "05-histograms-and-binnings",
        "notebook": "04.05-Histograms-and-Binnings.ipynb",
        "title": "Histogramlar ve Binleme",
        "nav_title": "4.5 Histogramlar",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/04.05-histograms-and-binnings.html",
        "en_label": "04.05 Histograms and Binnings",
        "preload_seaborn": False,
    },
    {
        "slug": "06-customizing-legends",
        "notebook": "04.06-Customizing-Legends.ipynb",
        "title": "Lejant Özelleştirme",
        "nav_title": "4.6 Lejantlar",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/04.06-customizing-legends.html",
        "en_label": "04.06 Customizing Legends",
        "preload_seaborn": False,
    },
    {
        "slug": "07-customizing-colorbars",
        "notebook": "04.07-Customizing-Colorbars.ipynb",
        "title": "Renk Çubukları Özelleştirme",
        "nav_title": "4.7 Renk Çubukları",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/04.07-customizing-colorbars.html",
        "en_label": "04.07 Customizing Colorbars",
        "preload_seaborn": False,
    },
    {
        "slug": "08-multiple-subplots",
        "notebook": "04.08-Multiple-Subplots.ipynb",
        "title": "Çoklu Alt Grafikler",
        "nav_title": "4.8 Alt Grafikler",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/04.08-multiple-subplots.html",
        "en_label": "04.08 Multiple Subplots",
        "preload_seaborn": False,
    },
    {
        "slug": "09-text-and-annotation",
        "notebook": "04.09-Text-and-Annotation.ipynb",
        "title": "Metin ve Açıklama",
        "nav_title": "4.9 Metin ve Açıklama",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/04.09-text-and-annotation.html",
        "en_label": "04.09 Text and Annotation",
        "preload_seaborn": False,
    },
    {
        "slug": "10-customizing-ticks",
        "notebook": "04.10-Customizing-Ticks.ipynb",
        "title": "Eksen İşaretleri Özelleştirme",
        "nav_title": "4.10 Eksen İşaretleri",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/04.10-customizing-ticks.html",
        "en_label": "04.10 Customizing Ticks",
        "preload_seaborn": False,
    },
    {
        "slug": "11-settings-and-stylesheets",
        "notebook": "04.11-Settings-and-Stylesheets.ipynb",
        "title": "Ayarlar ve Stil Sayfaları",
        "nav_title": "4.11 Ayarlar ve Stiller",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/04.11-settings-and-stylesheets.html",
        "en_label": "04.11 Settings and Stylesheets",
        "preload_seaborn": False,
    },
    {
        "slug": "12-three-dimensional-plotting",
        "notebook": "04.12-Three-Dimensional-Plotting.ipynb",
        "title": "Üç Boyutlu Çizim",
        "nav_title": "4.12 3B Çizim",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/04.12-three-dimensional-plotting.html",
        "en_label": "04.12 Three Dimensional Plotting",
        "preload_seaborn": False,
    },
    {
        "slug": "14-visualization-with-seaborn",
        "notebook": "04.14-Visualization-With-Seaborn.ipynb",
        "title": "Seaborn ile Görselleştirme",
        "nav_title": "4.14 Seaborn",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/04.14-visualization-with-seaborn.html",
        "en_label": "04.14 Visualization With Seaborn",
        "preload_seaborn": True,
    },
    {
        "slug": "15-further-resources",
        "notebook": "04.15-Further-Resources.ipynb",
        "title": "Daha Fazla Matplotlib Kaynağı",
        "nav_title": "4.15 Kaynaklar",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/04.15-further-matplotlib-resources.html",
        "en_label": "04.15 Further Resources",
        "preload_seaborn": False,
    },
]
