"""Pandas chapter metadata — PDS Handbook (TR)."""

PANDAS_CHAPTER = "03-pandas"

PANDAS_SECTIONS = [
    {
        "slug": "00-introduction",
        "notebook": "03.00-Introduction-to-Pandas.ipynb",
        "title": "Pandas ile Veri İşleme",
        "nav_title": "Pandas'a Giriş",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/03.00-introduction-to-pandas.html",
        "en_label": "03.00 Introduction to Pandas",
    },
    {
        "slug": "01-introducing-pandas-objects",
        "notebook": "03.01-Introducing-Pandas-Objects.ipynb",
        "title": "Pandas Nesnelerine Giriş",
        "nav_title": "3.1 Pandas Nesneleri",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/03.01-introducing-pandas-objects.html",
        "en_label": "03.01 Introducing Pandas Objects",
    },
    {
        "slug": "02-data-indexing-and-selection",
        "notebook": "03.02-Data-Indexing-and-Selection.ipynb",
        "title": "Veri İndeksleme ve Seçimi",
        "nav_title": "3.2 İndeksleme ve Seçim",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/03.02-data-indexing-and-selection.html",
        "en_label": "03.02 Data Indexing and Selection",
    },
    {
        "slug": "03-operations-in-pandas",
        "notebook": "03.03-Operations-in-Pandas.ipynb",
        "title": "Pandas'ta İşlemler",
        "nav_title": "3.3 Pandas İşlemleri",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/03.03-operations-in-pandas.html",
        "en_label": "03.03 Operations in Pandas",
    },
    {
        "slug": "04-missing-values",
        "notebook": "03.04-Missing-Values.ipynb",
        "title": "Eksik Veri",
        "nav_title": "3.4 Eksik Veri",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/03.04-missing-values.html",
        "en_label": "03.04 Missing Values",
    },
    {
        "slug": "05-hierarchical-indexing",
        "notebook": "03.05-Hierarchical-Indexing.ipynb",
        "title": "Hiyerarşik İndeksleme",
        "nav_title": "3.5 Hiyerarşik İndeks",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/03.05-hierarchical-indexing.html",
        "en_label": "03.05 Hierarchical Indexing",
    },
    {
        "slug": "06-concat-and-append",
        "notebook": "03.06-Concat-And-Append.ipynb",
        "title": "Birleştirme: Concat ve Append",
        "nav_title": "3.6 Concat ve Append",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/03.06-concat-and-append.html",
        "en_label": "03.06 Concat and Append",
    },
    {
        "slug": "07-merge-and-join",
        "notebook": "03.07-Merge-and-Join.ipynb",
        "title": "Merge ve Join",
        "nav_title": "3.7 Merge ve Join",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/03.07-merge-and-join.html",
        "en_label": "03.07 Merge and Join",
    },
    {
        "slug": "08-aggregation-and-grouping",
        "notebook": "03.08-Aggregation-and-Grouping.ipynb",
        "title": "Agregasyon ve Gruplama",
        "nav_title": "3.8 Agregasyon ve Gruplama",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html",
        "en_label": "03.08 Aggregation and Grouping",
    },
    {
        "slug": "09-pivot-tables",
        "notebook": "03.09-Pivot-Tables.ipynb",
        "title": "Pivot Tablolar",
        "nav_title": "3.9 Pivot Tablolar",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html",
        "en_label": "03.09 Pivot Tables",
    },
    {
        "slug": "10-working-with-strings",
        "notebook": "03.10-Working-With-Strings.ipynb",
        "title": "Dizelerle Çalışma",
        "nav_title": "3.10 Dizeler",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/03.10-working-with-strings.html",
        "en_label": "03.10 Working With Strings",
    },
    {
        "slug": "11-working-with-time-series",
        "notebook": "03.11-Working-with-Time-Series.ipynb",
        "title": "Zaman Serileri",
        "nav_title": "3.11 Zaman Serileri",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/03.11-working-with-time-series.html",
        "en_label": "03.11 Working with Time Series",
    },
    {
        "slug": "12-performance-eval-and-query",
        "notebook": "03.12-Performance-Eval-and-Query.ipynb",
        "title": "Performans: Değerlendirme ve Sorgu",
        "nav_title": "3.12 Performans ve Sorgu",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/03.12-performance-eval-and-query.html",
        "en_label": "03.12 Performance Eval and Query",
    },
    {
        "slug": "13-further-resources",
        "notebook": "03.13-Further-Resources.ipynb",
        "title": "Daha Fazla Pandas Kaynağı",
        "nav_title": "3.13 Kaynaklar",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/03.13-further-pandas-resources.html",
        "en_label": "03.13 Further Resources",
    },
]
