"""Scikit-Learn chapter metadata — PDS Handbook (TR)."""

SKLEARN_CHAPTER = "05-sklearn"

SKLEARN_SECTIONS = [
    {
        "slug": "00-introduction",
        "notebook": "05.00-Machine-Learning.ipynb",
        "title": "Makine Öğrenmesi",
        "nav_title": "Makine Öğrenmesine Giriş",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/05.00-machine-learning.html",
        "en_label": "05.00 Machine Learning",
        "preload_sklearn": False,
    },
    {
        "slug": "01-what-is-machine-learning",
        "notebook": "05.01-What-Is-Machine-Learning.ipynb",
        "title": "Makine Öğrenmesi Nedir?",
        "nav_title": "5.1 Makine Öğrenmesi Nedir?",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/05.01-what-is-machine-learning.html",
        "en_label": "05.01 What Is Machine Learning?",
        "preload_sklearn": False,
    },
    {
        "slug": "02-introducing-scikit-learn",
        "notebook": "05.02-Introducing-Scikit-Learn.ipynb",
        "title": "Scikit-Learn'e Giriş",
        "nav_title": "5.2 Scikit-Learn",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/05.02-introducing-scikit-learn.html",
        "en_label": "05.02 Introducing Scikit-Learn",
        "preload_sklearn": True,
    },
    {
        "slug": "03-hyperparameters-and-model-validation",
        "notebook": "05.03-Hyperparameters-and-Model-Validation.ipynb",
        "title": "Hiperparametreler ve Model Doğrulama",
        "nav_title": "5.3 Hiperparametreler",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/05.03-hyperparameters-and-model-validation.html",
        "en_label": "05.03 Hyperparameters and Model Validation",
        "preload_sklearn": True,
    },
    {
        "slug": "04-feature-engineering",
        "notebook": "05.04-Feature-Engineering.ipynb",
        "title": "Öznitelik Mühendisliği",
        "nav_title": "5.4 Öznitelik Mühendisliği",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/05.04-feature-engineering.html",
        "en_label": "05.04 Feature Engineering",
        "preload_sklearn": True,
    },
    {
        "slug": "05-naive-bayes",
        "notebook": "05.05-Naive-Bayes.ipynb",
        "title": "Naive Bayes Sınıflandırması",
        "nav_title": "5.5 Naive Bayes",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/05.05-naive-bayes.html",
        "en_label": "05.05 Naive Bayes",
        "preload_sklearn": True,
    },
    {
        "slug": "06-linear-regression",
        "notebook": "05.06-Linear-Regression.ipynb",
        "title": "Doğrusal Regresyon",
        "nav_title": "5.6 Doğrusal Regresyon",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/05.06-linear-regression.html",
        "en_label": "05.06 Linear Regression",
        "preload_sklearn": True,
    },
    {
        "slug": "07-support-vector-machines",
        "notebook": "05.07-Support-Vector-Machines.ipynb",
        "title": "Destek Vektör Makineleri",
        "nav_title": "5.7 SVM",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/05.07-support-vector-machines.html",
        "en_label": "05.07 Support Vector Machines",
        "preload_sklearn": True,
    },
    {
        "slug": "08-random-forests",
        "notebook": "05.08-Random-Forests.ipynb",
        "title": "Rastgele Ormanlar",
        "nav_title": "5.8 Rastgele Ormanlar",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/05.08-random-forests.html",
        "en_label": "05.08 Random Forests",
        "preload_sklearn": True,
    },
    {
        "slug": "09-principal-component-analysis",
        "notebook": "05.09-Principal-Component-Analysis.ipynb",
        "title": "Temel Bileşen Analizi",
        "nav_title": "5.9 PCA",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/05.09-principal-component-analysis.html",
        "en_label": "05.09 Principal Component Analysis",
        "preload_sklearn": True,
    },
    {
        "slug": "10-manifold-learning",
        "notebook": "05.10-Manifold-Learning.ipynb",
        "title": "Manifold Öğrenme",
        "nav_title": "5.10 Manifold",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/05.10-manifold-learning.html",
        "en_label": "05.10 Manifold Learning",
        "preload_sklearn": True,
    },
    {
        "slug": "11-k-means",
        "notebook": "05.11-K-Means.ipynb",
        "title": "K-Means Kümeleme",
        "nav_title": "5.11 K-Means",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/05.11-k-means.html",
        "en_label": "05.11 K-Means",
        "preload_sklearn": True,
    },
    {
        "slug": "12-gaussian-mixtures",
        "notebook": "05.12-Gaussian-Mixtures.ipynb",
        "title": "Gauss Karışımları",
        "nav_title": "5.12 Gauss Karışımları",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/05.12-gaussian-mixtures.html",
        "en_label": "05.12 Gaussian Mixtures",
        "preload_sklearn": True,
    },
    {
        "slug": "13-kernel-density-estimation",
        "notebook": "05.13-Kernel-Density-Estimation.ipynb",
        "title": "Çekirdek Yoğunluk Tahmini",
        "nav_title": "5.13 KDE",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/05.13-kernel-density-estimation.html",
        "en_label": "05.13 Kernel Density Estimation",
        "preload_sklearn": True,
    },
    {
        "slug": "14-image-features",
        "notebook": "05.14-Image-Features.ipynb",
        "title": "Görüntü Öznitelikleri",
        "nav_title": "5.14 Görüntü Öznitelikleri",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/05.14-image-features.html",
        "en_label": "05.14 Image Features",
        "preload_sklearn": True,
    },
    {
        "slug": "15-learning-more",
        "notebook": "05.15-Learning-More.ipynb",
        "title": "Daha Fazla Makine Öğrenmesi Kaynağı",
        "nav_title": "5.15 Kaynaklar",
        "en_url": "https://jakevdp.github.io/PythonDataScienceHandbook/05.15-learning-more.html",
        "en_label": "05.15 Learning More",
        "preload_sklearn": False,
    },
]
